// Code generated by goctl. DO NOT EDIT.
package types

type BaseDataInfo struct {
	Code    int    `json:"code"`           // Error code | 错误代码
	Message string `json:"message"`        // Message | 提示信息
	Data    string `json:"data,omitempty"` // Data | 数据
}

type BaseListInfo struct {
	Total uint64 `json:"total"`          // The total number of data | 数据总数
	Data  string `json:"data,omitempty"` // Data | 数据
}

type BaseMsgResp struct {
	Code    int    `json:"code"`    // Error code | 错误代码
	Message string `json:"message"` // Message | 提示信息
}

type DeliveryInfo struct {
	StationInfoList []StationInfo `json:"stationInfoList"` // 站点id
	PostsInfoList   []PostsInfo   `json:"postsInfoList"`   // 文章id
}

type DeliveryListInfo struct {
	Data []DeliveryLogInfo `json:"data"` // DeliveryInfo list data | DeliveryInfo列表数据
}

type DeliveryLogInfo struct {
	Id           uint64 `json:"id,optional"`
	Title        string `json:"title"`                 // 标题
	Source       string `json:"source,optional"`       // 来源
	DomainName   string `json:"domainName"`            // 域名
	DeliveryDate int64  `json:"deliveryDate,optional"` // 投放日期
	Deliverer    string `json:"deliverer,optional"`    // 投放人
	Status       int64  `json:"status,optional"`       // 投放状态
	Author       uint64 `json:"author,optional"`       // 作者
	WpCateIds    string `json:"wpCateIds,optional"`    // wp分类
	StationId    uint64 `json:"stationId,optional"`    // 站点id
	PostsId      uint64 `json:"postsId,optional"`      // 文章id
}

type DeliveryLogInfoResp struct {
	BaseDataInfo
	Data DeliveryLogInfo `json:"data"` // DeliveryLog information | DeliveryLog数据
}

type DeliveryLogListInfo struct {
	BaseListInfo
	Data []DeliveryLogInfo `json:"data"` // DeliveryLogInfo list data | DeliveryLogInfo列表数据
}

type DeliveryLogListResp struct {
	BaseDataInfo
	Data DeliveryLogListInfo `json:"data"` // DeliveryLog list data | DeliveryLog列表数据
}

type DeliveryLogReq struct {
	PageInfo
	Title        string `form:"title,optional"`        // 标题
	Source       string `form:"source,optional"`       // 来源
	DomainName   string `form:"domainName,optional"`   // 域名
	DeliveryDate int64  `form:"deliveryDate,optional"` // 投放日期
	Deliverer    string `form:"deliverer,optional"`    // 投放人
	Status       int64  `form:"status,optional"`       // 投放状态
	Author       uint64 `form:"author,optional"`       // 作者
}

type IDPathReq struct {
	Id uint64 `path:"id"` // ID  Required: true
}

type IDReq struct {
	Id uint64 `json:"id" validate:"number"` // ID Required: true
}

type IDsReq struct {
	Ids []uint64 `json:"ids"` // IDs Required: true
}

type PageInfo struct {
	Page     uint64 `form:"page" validate:"required,number,gt=0"`          // Page number | 第几页
	PageSize uint64 `form:"pageSize" validate:"required,number,lt=100000"` // Page size | 单页数据行数
}

type PostsInfo struct {
	Id         uint64 `json:"id,optional"`
	Title      string `json:"title"`               // 标题
	Source     string `json:"source"`              // 来源
	Author     int64  `json:"author"`              // 作者
	ThrownNum  int64  `json:"thrownNum"`           // 投放数量
	Categories string `json:"categories"`          // 分类
	CreateTime int64  `json:"createTime,optional"` //时间
	Content    string `json:"content"`             //详情
}

type PostsInfoResp struct {
	BaseDataInfo
	Data PostsInfo `json:"data"` // Posts information | Posts数据
}

type PostsListInfo struct {
	BaseListInfo
	Data []PostsInfo `json:"data"` // PostsInfo list data | PostsInfo列表数据
}

type PostsListResp struct {
	BaseDataInfo
	Data PostsListInfo `json:"data"` // Posts list data | Posts列表数据
}

type PostsReq struct {
	PageInfo
	Title      string `form:"title,optional"`      // 标题
	Source     string `form:"source,optional"`     // 来源
	Categories string `form:"categories,optional"` // 分类
	Author     int64  `form:"author,optional"`     // 作者
	CreateTime int64  `form:"createTime,optional"` // 时间
}

type StationInfo struct {
	Id           uint64  `json:"id,optional"`       // 主键
	DomainName   string  `json:"domainName"`        // 域名
	Ip           string  `json:"ip,optional"`       // 域名
	DomainYear   int64   `json:"domainYear"`        // 域名年份
	GoogleWeight float64 `json:"googleWeight"`      // 谷歌权重
	Type         string  `json:"type"`              // 网站类型
	Industry     string  `json:"industry"`          // 网站行业
	ArticlesNum  int64   `json:"articlesNum"`       // 文章数量
	UserName     string  `json:"userName,optional"` // 账号名
	PassWord     string  `json:"passWord,optional"` // 密码
	Status       int64   `json:"status,optional"`   // 状态
}

type StationInfoResp struct {
	BaseDataInfo
	Data StationInfo `json:"data"` // Station information | Station数据
}

type StationListInfo struct {
	BaseListInfo
	Data []StationInfo `json:"data"` // StationInfo list data | StationInfo列表数据
}

type StationListResp struct {
	BaseDataInfo
	Data StationListInfo `json:"data"` // Station list data | Station列表数据
}

type StationPostsInfo struct {
	Id    uint64 `json:"id"`
	Title string `json:"title"` // Title
}

type StationPostsResp struct {
	BaseDataInfo
	Data []StationPostsInfo `json:"data"` // Station Posts 返回体
}

type StationReq struct {
	PageInfo
	DomainName   string `form:"domainName,optional"`   // 域名
	Ip           string `form:"ip,optional"`           // ip
	DomainYear   int64  `form:"domainYear,optional"`   // 域名年份
	GoogleWeight string `form:"googleWeight,optional"` // 谷歌权重
	Type         string `form:"type,optional"`         // 网站类型
	Industry     string `form:"industry,optional"`     // 网站行业
	Status       int64  `form:"status,optional"`       // 状态
}
