// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: station.proto

// proto 包名

package greet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义请求体
type SayHelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SayHelloReq) Reset() {
	*x = SayHelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_station_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloReq) ProtoMessage() {}

func (x *SayHelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_station_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloReq.ProtoReflect.Descriptor instead.
func (*SayHelloReq) Descriptor() ([]byte, []int) {
	return file_station_proto_rawDescGZIP(), []int{0}
}

// 定义响应体
type SayHelloResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SayHelloResp) Reset() {
	*x = SayHelloResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_station_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResp) ProtoMessage() {}

func (x *SayHelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_station_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResp.ProtoReflect.Descriptor instead.
func (*SayHelloResp) Descriptor() ([]byte, []int) {
	return file_station_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_station_proto protoreflect.FileDescriptor

var file_station_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x61, 0x79, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x61, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x40, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x53, 0x61,
	0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x14, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x15, 0x5a, 0x13, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_station_proto_rawDescOnce sync.Once
	file_station_proto_rawDescData = file_station_proto_rawDesc
)

func file_station_proto_rawDescGZIP() []byte {
	file_station_proto_rawDescOnce.Do(func() {
		file_station_proto_rawDescData = protoimpl.X.CompressGZIP(file_station_proto_rawDescData)
	})
	return file_station_proto_rawDescData
}

var file_station_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_station_proto_goTypes = []interface{}{
	(*SayHelloReq)(nil),  // 0: station.SayHelloReq
	(*SayHelloResp)(nil), // 1: station.SayHelloResp
}
var file_station_proto_depIdxs = []int32{
	0, // 0: station.Greet.SayHello:input_type -> station.SayHelloReq
	1, // 1: station.Greet.SayHello:output_type -> station.SayHelloResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_station_proto_init() }
func file_station_proto_init() {
	if File_station_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_station_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_station_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_station_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_station_proto_goTypes,
		DependencyIndexes: file_station_proto_depIdxs,
		MessageInfos:      file_station_proto_msgTypes,
	}.Build()
	File_station_proto = out.File
	file_station_proto_rawDesc = nil
	file_station_proto_goTypes = nil
	file_station_proto_depIdxs = nil
}
