// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	base "api/internal/handler/base"
	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/station/api/hello",
				Handler: base.HelloHandler(serverCtx),
			},
		},
	)
}
