// Code generated by goctl. DO NOT EDIT.
// Source: station.proto

package server

import (
	"context"

	"rpc/example/proto/greet"
	"rpc/internal/logic/greet"
	"rpc/internal/svc"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	greet.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

// 定义一个 SayHello 一元 rpc 方法，请求体和响应体必填。
func (s *GreetServer) SayHello(ctx context.Context, in *greet.SayHelloReq) (*greet.SayHelloResp, error) {
	l := greetlogic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
