// Code generated by goctl. DO NOT EDIT.
// Source: station.proto

package server

import (
	"context"

	"rpc/internal/logic/deliverylog"
	"rpc/internal/svc"
	"rpc/station"
)

type DeliveryLogServer struct {
	svcCtx *svc.ServiceContext
	station.UnimplementedDeliveryLogServer
}

func NewDeliveryLogServer(svcCtx *svc.ServiceContext) *DeliveryLogServer {
	return &DeliveryLogServer{
		svcCtx: svcCtx,
	}
}

func (s *DeliveryLogServer) AddDelivery(ctx context.Context, in *station.DeliveryLogListInfo) (*station.BaseDataInfo, error) {
	l := deliveryloglogic.NewAddDeliveryLogic(ctx, s.svcCtx)
	return l.AddDelivery(in)
}

func (s *DeliveryLogServer) GetDeliveryList(ctx context.Context, in *station.DeliveryInfo) (*station.DeliveryLogListInfo, error) {
	l := deliveryloglogic.NewGetDeliveryListLogic(ctx, s.svcCtx)
	return l.GetDeliveryList(in)
}

func (s *DeliveryLogServer) AddDeliveryLog(ctx context.Context, in *station.DeliveryLogInfo) (*station.DeliveryLogInfo, error) {
	l := deliveryloglogic.NewAddDeliveryLogLogic(ctx, s.svcCtx)
	return l.AddDeliveryLog(in)
}

func (s *DeliveryLogServer) UpdateDeliveryLog(ctx context.Context, in *station.DeliveryLogInfo) (*station.DeliveryLogInfo, error) {
	l := deliveryloglogic.NewUpdateDeliveryLogLogic(ctx, s.svcCtx)
	return l.UpdateDeliveryLog(in)
}

func (s *DeliveryLogServer) UpdateStatus(ctx context.Context, in *station.IDStatusReq) (*station.BaseDataInfo, error) {
	l := deliveryloglogic.NewUpdateStatusLogic(ctx, s.svcCtx)
	return l.UpdateStatus(in)
}

func (s *DeliveryLogServer) DeleteDeliveryLog(ctx context.Context, in *station.IDPathReq) (*station.BaseDataInfo, error) {
	l := deliveryloglogic.NewDeleteDeliveryLogLogic(ctx, s.svcCtx)
	return l.DeleteDeliveryLog(in)
}

func (s *DeliveryLogServer) QueryDeliveryLog(ctx context.Context, in *station.DeliveryLogReq) (*station.DeliveryLogListInfo, error) {
	l := deliveryloglogic.NewQueryDeliveryLogLogic(ctx, s.svcCtx)
	return l.QueryDeliveryLog(in)
}
