// Code generated by goctl. DO NOT EDIT.
// Source: station.proto

package server

import (
	"context"

	"rpc/internal/logic/stationpostsrelation"
	"rpc/internal/svc"
	"rpc/station"
)

type StationPostsRelationServer struct {
	svcCtx *svc.ServiceContext
	station.UnimplementedStationPostsRelationServer
}

func NewStationPostsRelationServer(svcCtx *svc.ServiceContext) *StationPostsRelationServer {
	return &StationPostsRelationServer{
		svcCtx: svcCtx,
	}
}

func (s *StationPostsRelationServer) AddStationPostsRelation(ctx context.Context, in *station.StationPostsRelationInfo) (*station.StationPostsRelationInfo, error) {
	l := stationpostsrelationlogic.NewAddStationPostsRelationLogic(ctx, s.svcCtx)
	return l.AddStationPostsRelation(in)
}

func (s *StationPostsRelationServer) UpdateStationPostsRelation(ctx context.Context, in *station.StationPostsRelationInfo) (*station.StationPostsRelationInfo, error) {
	l := stationpostsrelationlogic.NewUpdateStationPostsRelationLogic(ctx, s.svcCtx)
	return l.UpdateStationPostsRelation(in)
}

func (s *StationPostsRelationServer) DeleteStationPostsRelation(ctx context.Context, in *station.IDPathReq) (*station.BaseDataInfo, error) {
	l := stationpostsrelationlogic.NewDeleteStationPostsRelationLogic(ctx, s.svcCtx)
	return l.DeleteStationPostsRelation(in)
}
