// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postsFieldNames          = builder.RawFieldNames(&Posts{})
	postsRows                = strings.Join(postsFieldNames, ",")
	postsRowsExpectAutoSet   = strings.Join(stringx.Remove(postsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postsRowsWithPlaceHolder = strings.Join(stringx.Remove(postsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postsModel interface {
		Insert(ctx context.Context, data *Posts) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Posts, error)
		Update(ctx context.Context, data *Posts) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPostsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Posts struct {
		Id         uint64         `db:"id"`
		Title      sql.NullString `db:"title"`      // 标题
		Source     sql.NullString `db:"source"`     // 来源
		Author     sql.NullInt64  `db:"author"`     // 作者
		ThrownNum  sql.NullInt64  `db:"thrown_num"` // 投放数量
		Categories sql.NullString `db:"categories"` // 分类
		Creater    sql.NullString `db:"creater"`    // 创建人
		CreateAt   time.Time      `db:"create_at"`  // 创建时间
		Modifier   sql.NullString `db:"modifier"`   // 修改人
		UpdateAt   time.Time      `db:"update_at"`  // 修改时间
	}
)

func newPostsModel(conn sqlx.SqlConn) *defaultPostsModel {
	return &defaultPostsModel{
		conn:  conn,
		table: "`posts`",
	}
}

func (m *defaultPostsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPostsModel) FindOne(ctx context.Context, id uint64) (*Posts, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postsRows, m.table)
	var resp Posts
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostsModel) Insert(ctx context.Context, data *Posts) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, postsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Source, data.Author, data.ThrownNum, data.Categories, data.Creater, data.Modifier)
	return ret, err
}

func (m *defaultPostsModel) Update(ctx context.Context, data *Posts) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Source, data.Author, data.ThrownNum, data.Categories, data.Creater, data.Modifier, data.Id)
	return err
}

func (m *defaultPostsModel) tableName() string {
	return m.table
}
