// Code generated by goctl. DO NOT EDIT.
// Source: station.proto

package station

import (
	"context"

	"rpc/station"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseDataInfo             = station.BaseDataInfo
	BaseListInfo             = station.BaseListInfo
	DeliveryInfo             = station.DeliveryInfo
	DeliveryLogInfo          = station.DeliveryLogInfo
	DeliveryLogListInfo      = station.DeliveryLogListInfo
	DeliveryLogReq           = station.DeliveryLogReq
	IDPathReq                = station.IDPathReq
	IDStatusReq              = station.IDStatusReq
	PageInfo                 = station.PageInfo
	PostsInfo                = station.PostsInfo
	PostsListInfo            = station.PostsListInfo
	PostsReq                 = station.PostsReq
	PostsStationInfo         = station.PostsStationInfo
	PostsStationResp         = station.PostsStationResp
	StationInfo              = station.StationInfo
	StationInfoResp          = station.StationInfoResp
	StationListInfo          = station.StationListInfo
	StationListResp          = station.StationListResp
	StationPostsInfo         = station.StationPostsInfo
	StationPostsRelationInfo = station.StationPostsRelationInfo
	StationPostsResp         = station.StationPostsResp
	StationReq               = station.StationReq
	UUIDReq                  = station.UUIDReq
	UsersInfo                = station.UsersInfo
	UsersListInfo            = station.UsersListInfo
	UsersReq                 = station.UsersReq

	Station interface {
		AddStation(ctx context.Context, in *StationInfo, opts ...grpc.CallOption) (*StationInfo, error)
		UpdateStation(ctx context.Context, in *StationInfo, opts ...grpc.CallOption) (*StationInfo, error)
		DeleteStation(ctx context.Context, in *IDPathReq, opts ...grpc.CallOption) (*BaseDataInfo, error)
		QueryStation(ctx context.Context, in *StationReq, opts ...grpc.CallOption) (*StationListInfo, error)
		GetStationAll(ctx context.Context, in *IDPathReq, opts ...grpc.CallOption) (*StationListInfo, error)
		GetStation(ctx context.Context, in *IDPathReq, opts ...grpc.CallOption) (*StationInfo, error)
		QueryPosts(ctx context.Context, in *IDPathReq, opts ...grpc.CallOption) (*StationPostsResp, error)
	}

	defaultStation struct {
		cli zrpc.Client
	}
)

func NewStation(cli zrpc.Client) Station {
	return &defaultStation{
		cli: cli,
	}
}

func (m *defaultStation) AddStation(ctx context.Context, in *StationInfo, opts ...grpc.CallOption) (*StationInfo, error) {
	client := station.NewStationClient(m.cli.Conn())
	return client.AddStation(ctx, in, opts...)
}

func (m *defaultStation) UpdateStation(ctx context.Context, in *StationInfo, opts ...grpc.CallOption) (*StationInfo, error) {
	client := station.NewStationClient(m.cli.Conn())
	return client.UpdateStation(ctx, in, opts...)
}

func (m *defaultStation) DeleteStation(ctx context.Context, in *IDPathReq, opts ...grpc.CallOption) (*BaseDataInfo, error) {
	client := station.NewStationClient(m.cli.Conn())
	return client.DeleteStation(ctx, in, opts...)
}

func (m *defaultStation) QueryStation(ctx context.Context, in *StationReq, opts ...grpc.CallOption) (*StationListInfo, error) {
	client := station.NewStationClient(m.cli.Conn())
	return client.QueryStation(ctx, in, opts...)
}

func (m *defaultStation) GetStationAll(ctx context.Context, in *IDPathReq, opts ...grpc.CallOption) (*StationListInfo, error) {
	client := station.NewStationClient(m.cli.Conn())
	return client.GetStationAll(ctx, in, opts...)
}

func (m *defaultStation) GetStation(ctx context.Context, in *IDPathReq, opts ...grpc.CallOption) (*StationInfo, error) {
	client := station.NewStationClient(m.cli.Conn())
	return client.GetStation(ctx, in, opts...)
}

func (m *defaultStation) QueryPosts(ctx context.Context, in *IDPathReq, opts ...grpc.CallOption) (*StationPostsResp, error) {
	client := station.NewStationClient(m.cli.Conn())
	return client.QueryPosts(ctx, in, opts...)
}
